name: Test Build

on:
  workflow_dispatch:  # 手动触发
  push:
    paths:
      - '.github/workflows/**'
      - '*.py'
      - '*.js'
      - '*.html'
      - '*.css'

jobs:
  test-macos-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_macos.txt
        
    - name: Quick build test
      run: |
        echo "Testing PyInstaller basic functionality..."
        pyinstaller --version
        
        echo "Testing app.py import..."
        python -c "import app; print('✅ app.py imports successfully')"
        
        echo "Starting build..."
        pyinstaller \
          --onefile \
          --windowed \
          --name "Nano-Banana-Test" \
          --add-data "index.html:." \
          --add-data "script.js:." \
          --add-data "api.js:." \
          --add-data "utils.js:." \
          --add-data "styles.css:." \
          app.py
          
    - name: Verify test build
      run: |
        echo "Build contents:"
        ls -la dist/
        
        if [ -d "dist/Nano-Banana-Test.app" ]; then
          echo "✅ Test build successful!"
          echo "App size: $(du -sh dist/Nano-Banana-Test.app | cut -f1)"
          echo "App structure:"
          find dist/Nano-Banana-Test.app -type f | head -10
        else
          echo "❌ Test build failed"
          exit 1
        fi
        
    - name: Upload test build
      uses: actions/upload-artifact@v3
      with:
        name: test-build-macos
        path: dist/Nano-Banana-Test.app
        retention-days: 5

  test-windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Quick Windows build test
      run: |
        echo "Testing Windows build..."
        pyinstaller --version
        
        pyinstaller --onefile --name "Nano-Banana-Test-Win" --add-data "index.html;." --add-data "script.js;." --add-data "api.js;." --add-data "utils.js;." --add-data "styles.css;." app.py
        
    - name: Verify Windows build
      run: |
        echo "Build contents:"
        dir dist
        
        if (Test-Path "dist/Nano-Banana-Test-Win.exe") {
          echo "✅ Windows test build successful!"
          $size = (Get-Item "dist/Nano-Banana-Test-Win.exe").Length / 1MB
          echo "Exe size: $([math]::Round($size, 1)) MB"
        } else {
          echo "❌ Windows test build failed"
          exit 1
        }
        
    - name: Upload Windows test build
      uses: actions/upload-artifact@v3
      with:
        name: test-build-windows
        path: dist/Nano-Banana-Test-Win.exe
        retention-days: 5